aws_region                = "eu-west-1"
iam_group_name            = "cmtr-0g1jc0vy-iam-group"
iam_policy_name           = "cmtr-0g1jc0vy-iam-policy"
iam_role_name             = "cmtr-0g1jc0vy-iam-role"
iam_instance_profile_name = "cmtr-0g1jc0vy-iam-instance-profile"
bucket_name               = "cmtr-0g1jc0vy-bucket-1779889958"
project_tag               = "cmtr-0g1jc0vy"
