aws_region                = "eu-west-1"
iam_group_name            = "cmtr-0g1jc0vy-iam-group"
iam_policy_name           = "REPLACE_ME_iam_policy_name"
iam_role_name             = "REPLACE_ME_iam_role_name"
iam_instance_profile_name = "REPLACE_ME_iam_instance_profile_name"
bucket_name               = "REPLACE_ME_bucket_name"
project_tag               = "cmtr-0g1jc0vy"
